package io.github.t4skforce.deepviolet.jackson.dataformat.tls.model.record.handshake;

/**
 * <strong>This class is generated by {@link io.github.t4skforce.deepviolet.generators.impl.TlsCipherSuiteCodeGenerator}. DO NOT MODIFY!</strong><br/>
 *
 */
class CipherSuiteTest {

}
