package io.github.t4skforce.deepviolet.jackson.dataformat.tls.model.record.handshake;

import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * <strong>This class is generated by {@link io.github.t4skforce.deepviolet.generators.impl.TlsCompressionMethodCodeGenerator}.
 * DO NOT MODIFY!</strong><br/>
 *
 */
class CompressionMethodTest {
  public static final Date UPDATED = new Date(1616628074000L);

  @Test
  public void testNull() throws Exception {
    CompressionMethod compression = CompressionMethod.NULL;
    Assertions.assertEquals("NULL", compression.getName());
    Assertions.assertEquals(0x00, compression.getValue());
    Assertions.assertEquals(compression, CompressionMethod.of(0x00));
    Assertions.assertEquals(compression, CompressionMethod.of("NULL"));
  }

  @Test
  public void testDeflate() throws Exception {
    CompressionMethod compression = CompressionMethod.DEFLATE;
    Assertions.assertEquals("DEFLATE", compression.getName());
    Assertions.assertEquals(0x01, compression.getValue());
    Assertions.assertEquals(compression, CompressionMethod.of(0x01));
    Assertions.assertEquals(compression, CompressionMethod.of("DEFLATE"));
  }

  @Test
  public void testLzs() throws Exception {
    CompressionMethod compression = CompressionMethod.LZS;
    Assertions.assertEquals("LZS", compression.getName());
    Assertions.assertEquals(0x40, compression.getValue());
    Assertions.assertEquals(compression, CompressionMethod.of(0x40));
    Assertions.assertEquals(compression, CompressionMethod.of("LZS"));
  }

  @Test
  public void testTestFullRange() throws Exception {
    for (int i=0x00; i<=0xFF; i++) {
      Assertions.assertNotNull(CompressionMethod.of(i), String.format("CompressionMethod.of(0x%02X)", i));
      Assertions.assertTrue(CompressionMethod.of(i) == CompressionMethod.of(i));
      Assertions.assertTrue(CompressionMethod.of(i) == CompressionMethod.of(CompressionMethod.of(i).getName()));
      Assertions.assertTrue(CompressionMethod.of(CompressionMethod.of(i).toString()) == CompressionMethod.of(CompressionMethod.of(i).getName()));
    }
  }
}
