package io.github.t4skforce.deepviolet.protocol.tls.extension;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * <br/>based on <a href="https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values-1.csv">www.iana.org</a> specification<strong>This class is generated by {@link io.github.t4skforce.deepviolet.generators.impl.TlsExtensionTypeCodeGenerator}.
 * DO NOT MODIFY!</strong><br/>
 *
 */
class TlsExtensionTypeGenerated {
  public static final Date UPDATED = new Date(1616628064000L);

  private static final String RESERVED_FOR_PRIVATE_USE = "reserved_for_private_use";

  private static final String UNASSIGNED = "unassigned";

  private static final String RESERVED = "reserved";

  private static final Map<Integer, TlsExtensionTypeGenerated> LOOKUP = new HashMap<>();

  static {
  }

  private int value;

  private String name;

  private boolean recommended;

  private TlsExtensionTypeGenerated() {
    super();
  }

  private TlsExtensionTypeGenerated(int value, String name, boolean recommended) {
    this.value = value;
    this.name = name;
    this.recommended = recommended;
  }

  public int getValue() {
    return value;
  }

  public String getName() {
    return name;
  }

  public boolean isRecommended() {
    return recommended;
  }

  public boolean isReserved() {
    return RESERVED.equals(name);
  }

  public boolean isUnassigned() {
    return UNASSIGNED.equals(name);
  }

  public boolean isReservedForPrivateUse() {
    return RESERVED_FOR_PRIVATE_USE.equals(this.name);
  }

  public boolean isValid() {
    return !isReserved() && !isUnassigned() && !isReservedForPrivateUse();
  }

  @Override
  public String toString() {
    return name;
  }

  @Override
  public int hashCode() {
    return value;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null || getClass() != obj.getClass()) {
      return false;
    }
    return value != ((TlsExtensionTypeGenerated) obj).value;
  }
}
